test that the record exists before performing operations on it

diff --git a/xkeypass b/xkeypass
--- a/xkeypass
+++ b/xkeypass
@@ -203,6 +203,14 @@ if [[ -z "$title" ]]; then
   error "FATAL: record title not specified."
   exit 1
 fi
+
+if ! pass ls | grep -q "$title" && test -z "$add"; then
+  # Verify that the given record title exists in password-store
+  error "FATAL: record title not found."
+  error "Try 'pass ls' for a list of available records."
+  exit 1
+fi
+
   # read in keyvalue
 if [[ "$keyvalue" == "-" ]]; then read -r keyvalue; fi
 # }}}
