dropped the tmpfile from getpw() in favor of streams

diff --git a/xkeypass b/xkeypass
--- a/xkeypass
+++ b/xkeypass
@@ -30,12 +30,10 @@ cleanup() {
 getpw() {
   local key="$1"
   local title="$2"
-  local tmpfile="$3"
 
-  if pass show "$title" > "$tmpfile"; then
-    jshon -e "$key" -u -F "$tmpfile"
-  else
-    error "$(cat "$tmpfile")"
+  if ! pass show "$title" | jshon -e "$key" -u ; then
+    error "We failed to retrieve the password."
+    exit 1
   fi
   cleanup
 }
@@ -238,7 +236,7 @@ fi
 # Retrieve {{{1
 if [[ -n "$get" ]]; then
   verbose "Extracting $key from $title"
-  getpw "$key" "$title" "$tmpfile"
+  getpw "$key" "$title"
 fi
 # }}}
 # select {{{1
@@ -275,7 +273,7 @@ fi
 # xkey type {{{1
 if [[ -n "$xkey" ]]; then
   if ! type xdokey &> /dev/null; then echo "ERROR: Missing dependency: xdokey" 1>&2; exit 1; fi
-  if ! xdokey < <(getpw "$key" "$title" "$tmpfile"); then
+  if ! xdokey < <(getpw "$key" "$title"); then
     error "FATAL: error with xdokey"
   fi
 fi
